#resolver: lts-6.10
#resolver: nightly-2016-08-31
#resolver: lts-7.01
#resolver: lts-8.12
resolver: lts-9.10
packages:
- oceanogr/
- gamma-n/
- observation/
- ../GSW-Haskell/
- ../../GitHub/hnetcdf-0.4.0.99/
#extra-deps: []
extra-deps:
- hnetcdf-0.4.0.99
- hmatrix-repa-0.1.2.2
- repa-3.4.1.3
- repa-io-3.4.1.1
flags: {}
extra-package-dbs: []
