#resolver: lts-6.10
#resolver: nightly-2016-08-31
#resolver: lts-7.01
#resolver: lts-8.12
#resolver: lts-9.10
#resolver: lts-11.18
#resolver: lts-12.16
#resolver: lts-12.26
#resolver: lts-13.9
#resolver: lts-13.17
resolver: lts-14.27

packages:
- .
extra-deps: []
flags: {}
extra-package-dbs: []
